---

- name: install
  apt:
    name:
      - vim-gtk3
  become: true
  become_method: sudo
  become_user: root

- name: check vim exist
  stat:
    path: "{{ configure_prefix }}/bin/vim"
  register: vim_stat

- name: display compile message
  debug:
    msg:
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
      - '***                                                     ***'
      - '*** We are going to compile and install Vim from source ***'
      - '*** Warning: This will try to unistall Vim first        ***'
      - '***                                                     ***'
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
  tags:
    - compile
  when: not vim_stat.stat.exists

- name: include task from comile.yml
  include_tasks: compile.yml
  tags:
    - compile
  when: not vim_stat.stat.exists

- name: display vimrc message
  debug:
    msg:
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
      - '***                                                     ***'
      - '*** We are going to copy the choosen vimrc file         ***'
      - '***                                                     ***'
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
  tags:
    - vimrc

- name: include task from vimrc.yml
  include_tasks: vimrc.yml
  tags:
    - vimrc
