---

- name: install
  apt:
    name:
#      - vim-gtk3
      - wl-clipboard
      - xsel
  become: true
  become_method: sudo
  become_user: root

- name: install pip
  pip:
    name:
      - pyflakes
      - pep8
      - pylint
      - ipython
    extra_args: "{{ '--break-system-packages' if (((ansible_distribution|lower) == 'debian') and ((ansible_distribution_version|int) in [9, 10, 11, 12])) else '' }}"
  become: true
  become_user: root
  become_method: sudo

- name: check vim exist
  stat:
    path: "{{ configure_prefix }}/bin/vim"
  register: vim_stat

- name: display compile message
  debug:
    msg:
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
      - '***                                                     ***'
      - '*** We are going to compile and install Vim from source ***'
      - '*** Warning: This will try to unistall Vim first        ***'
      - '***                                                     ***'
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
  tags:
    - compile
  when: not vim_stat.stat.exists

- name: include task from comile.yml
  include_tasks: compile.yml
  tags:
    - compile
  when: not vim_stat.stat.exists

- name: display vimrc message
  debug:
    msg:
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
      - '***                                                     ***'
      - '*** We are going to copy the choosen vimrc file         ***'
      - '***                                                     ***'
      - '***********************************************************'
      - '***********************************************************'
      - '***********************************************************'
  tags:
    - vimrc

- name: include task from vimrc.yml
  include_tasks: vimrc.yml
  tags:
    - vimrc
