---
- name: set fact for requirements_dest
  set_fact:
    requirements_dest: /tmp/requirements.txt
  tags:
    - vimrc

- name: copy requirements to remote server
  copy:
    src: "{{ requirements_path }}"
    dest: "{{ requirements_dest }}"
  tags:
    - vimrc

- name: pip install -r requirements
  become: yes
  pip:
    requirements: "{{ requirements_dest }}"
    extra_args: "--break-system-packages"
  tags:
    - vimrc
